{% set name = "markdown-include" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmacmackin/markdown-include/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5944cac326e3f071188ce902c6edeacbf5ae7c33273875594debf93e5d850a72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - markdown >=3.0
    - python >=2.7

test:
  imports:
    - markdown_include
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cmacmackin/markdown-include/
  summary:  Provides syntax for Python-Markdown which allows for the inclusion of the contents of other Markdown documents. 
  description: |
    This is an extension to Python-Markdown which provides an "include" function,
    similar to that found in LaTeX (and also the C pre-processor and Fortran). I
    originally wrote it for my FORD Fortran auto-documentation generator.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
