{% set name = "markdown-include" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8f6b6f4e8b506cbe773d7e26c74a97d1354c35f3a3452d3449140a8f578d665

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm >=6.2
  run:
    - markdown >=3.0
    - python >=3.7

test:
  imports:
    - markdown_include
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cmacmackin/markdown-include/
  summary: Provides syntax for Python-Markdown which allows for the inclusion of the contents of other Markdown documents.
  description: |
    This is an extension to Python-Markdown which provides an "include" function,
    similar to that found in LaTeX (and also the C pre-processor and Fortran). I
    originally wrote it for my FORD Fortran auto-documentation generator.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
